name: Deploy para Firebase Hosting em PRs
on: pull_request
permissions:
    checks: write
    contents: read
    pull-requests: write

jobs:
    build_and_test:
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository}}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm run teste

            - name: Build Application
              run: npm run build

            - name: Copy Firebase Files in dist folder
              run: 
                cp firebase.json dist/
                cp .firebaserc dist/

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: build-files
                path: dist/

    deploy_to_preview:
        needs: build_and_test
        runs-on: ubuntu-latest

        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                name: build-files
            
            - name: List files
              run: ls -R

            - name: Deploy to Firebase Hosting
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                repoToken: ${{ secrets.GITHUB_TOKEN }}
                firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOKINGUP_665F9 }}
                projectId: cookingup-665f9